
### GET all customers:
GET http://localhost:5000/selectCustomers

#### ### Get customer by ID
GET  http://localhost:5000/selectCustomers/1/


#### Post or upload or create a new customer
POST  http://localhost:5000/selectCustomers/
Content-Type: application/json

{
  "name": "Lary",
  "email": "Larry@gmail.com",
  "password":"Larryy@123",
  "address":"5-46",
  "phoneNumber": 9766554433
}

####

### Update a customer
PUT http://localhost:5000/selectCustomers/1/
Content-Type: application/json

{
    "name": "daniel vettori",
    "email": "daniel@gmail.com",
    "password": "daniel@123",
    "address": "3-33,high-line street",
    "phoneNumber": 9788554321
}

### Delete a customer by ID
DELETE http://localhost:5000/selectCustomers/5/






